//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int companyId { get; set; }
        public string companyCode { get; set; }
        public string companyName { get; set; }
        public string url { get; set; }
        public string dbname { get; set; }
        public bool active { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    }
}
